---
language: ruby

script: bundle exec rake

before_install:
  - sudo pip install lxml
  - bash ./script/alpino.sh

env:
  - ALPINO_HOME=./Alpino

rvm:
  - 2.1

notifications:
  email:
    recipients:
      - development+travis-opener@olery.com

    on_success: change
    on_failure: change

cache: bundler

branches:
  only:
    - master
